export const UPDATE_FORM_INPUT = 'UPDATE_FORM_INPUT';
export const UPDATE_FORM_ERROR = 'UPDATE_FORM_ERROR';
export const ADD_VALUE_TO_COUNT = 'ADD_VALUE_TO_COUNT';
export const RESET_COUNT = 'RESET_COUNT';
