// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from '@lezer/lr';
export const parser = LRParser.deserialize({
  version: 14,
  states: 'tOQOPOOOVOPOOO_OQOOOYOPOOOdOPOOQOOOOO',
  stateData: 'o~OQPO~ORROVQO~OSSO~OTTO~ORQTST~',
  goto: 'QPP',
  nodeNames: '⚠ Program Type Scope Description EOF',
  maxTerm: 7,
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData:
    "*q~R]OYzYZ!cZxzxy!hy![z![!]'s!]#Yz#Y#Z(W#Z;'Sz;'S;=`!]<%l~z~Oz~~!cQ!PSSQOYzZ;'Sz;'S;=`!]<%lOzQ!`P;=`<%lz~!hOT~~!mZSQOY!hYZ#`Zr!hrszsy!hyz%lz#O!h#O#P&f#P;'S!h;'S;=`'m<%lO!h~#cWOr#`sy#`yz#{z#O#`#O#P$j#P;'S#`;'S;=`%f<%lO#`~$QWR~Or#`sy#`yz#{z#O#`#O#P$j#P;'S#`;'S;=`%f<%lO#`~$mRO;'S#`;'S;=`$v;=`O#`~$yXOr#`sy#`yz#{z#O#`#O#P$j#P;'S#`;'S;=`%f;=`<%l#`<%lO#`~%iP;=`<%l#`~%sZR~SQOY!hYZ#`Zr!hrszsy!hyz%lz#O!h#O#P&f#P;'S!h;'S;=`'m<%lO!h~&kUSQOY!hYZ#`Z;'S!h;'S;=`&};=`<%l#`<%lO!h~'QXOr#`sy#`yz#{z#O#`#O#P$j#P;'S#`;'S;=`%f;=`<%l!h<%lO#`~'pP;=`<%l!hR'zSVPSQOYzZ;'Sz;'S;=`!]<%lOz~(]WSQOYzZ#Xz#X#Y(u#Y#]z#]#^*Y#^;'Sz;'S;=`!]<%lOz~(zUSQOYzZ#Tz#T#U)^#U;'Sz;'S;=`!]<%lOz~)cUSQOYzZ#hz#h#i)u#i;'Sz;'S;=`!]<%lOz~)|SQ~SQOYzZ;'Sz;'S;=`!]<%lOz~*_USQOYzZ#lz#l#m)u#m;'Sz;'S;=`!]<%lOz",
  tokenizers: [0, 1],
  topRules: { Program: [0, 1] },
  tokenPrec: 25,
});
