// This file was generated by lezer-generator. You probably shouldn't edit it.
export const Program = 1,
  Summary = 2,
  Type = 3,
  Scope = 4,
  Whitespace = 5,
  Description = 6,
  NewLines = 7,
  Body = 8;
