/**
 * @since 20180613 21:03
 * @author vivaxy
 */

export const ON_CANVAS_CLICK = 'ON_CANVAS_CLICK';
export const ON_CANVAS_TOUCH_START = 'ON_CANVAS_TOUCH_START';
export const ON_CANVAS_TOUCH_MOVE = 'ON_CANVAS_TOUCH_MOVE';
export const ON_CANVAS_TOUCH_END = 'ON_CANVAS_TOUCH_END';

export const APPLY_RENDER = 'APPLY_RENDER';
export const ON_RENDER_PREPARING = 'ON_RENDER_PREPARING';
export const ON_RENDER_PREPARED = 'ON_RENDER_PREPARED';
export const ON_RENDERING = 'ON_RENDERING';
export const ON_RENDERED = 'ON_RENDERED';

export const ON_BUTTON_CLICK = 'ON_BUTTON_CLICK';
export const ON_EMPTY_SPACE_CLICK = 'ON_EMPTY_SPACE_CLICK';
