/**
 * @since 2018-05-20 14:07:00
 * @author vivaxy
 */

export const REQUEST_AN_UNSORTED_ARRAY = 'REQUEST_AN_UNSORTED_ARRAY';
export const REQUEST_ANIMATION_ACTIONS = 'REQUEST_ANIMATION_ACTIONS';
export const APPLY_AN_ANIMATION_ACTION = 'APPLY_AN_ANIMATION_ACTION';
export const ON_ANIMATION_ACTIONS_START = 'ON_ANIMATION_ACTIONS_START';
export const ON_AN_ANIMATION_ACTION_START = 'ON_AN_ANIMATION_ACTION_START';
export const ON_AN_ANIMATION_ACTION_END = 'ON_AN_ANIMATION_ACTION_END';
export const ON_ANIMATION_ACTIONS_END = 'ON_ANIMATION_ACTIONS_END';
