/**
 * @since 20180710 14:17
 * @author vivaxy
 */

export const APPLY_OPEN_DB = 'APPLY_OPEN_DB';
export const ON_OPEN_DB_PREPARED = 'ON_OPEN_DB_PREPARED';

export const ON_IDB_OPEN_ERROR = 'ON_IDB_OPEN_ERROR';
export const ON_IDB_OPEN_SUCCESS = 'ON_IDB_OPEN_SUCCESS';
export const ON_IDB_OPEN_UPGRADE_NEEDED = 'ON_IDB_OPEN_UPGRADE_NEEDED';
export const ON_IDB_OPEN_BLOCKED = 'ON_IDB_OPEN_BLOCKED';

export const APPLY_RENDER_TABLE = 'APPLY_RENDER_TABLE';
