export const CREATE_A_NEW_ARRAY = 'CREATE_A_NEW_ARRAY';
export const PUSH_TO_AN_ARRAY = 'PUSH_TO_AN_ARRAY';
export const MARK_ARRAY_INDEX = 'MARK_ARRAY_INDEX';
export const COMPARE = 'COMPARE';
export const ASSIGN = 'ASSIGN';
export const DESTROY_NEW_ARRAYS = 'DESTROY_NEW_ARRAYS';
